Specification-Title=${project.name}
Specification-Version=${project.artifact.selectedVersion.majorVersion}.${project.artifact.selectedVersion.minorVersion}
Specification-Vendor=${project.organization.name}
Implementation-Title=${project.name}
Implementation-Version=${arkcase.version}
Implementation-Vendor-Id=${arkcase.groupId}
Implementation-Vendor=${project.organization.name}
Implementation-URL=${project.organization.url}
Build-Time=${maven.build.timestamp}
SCM-Branch=${scmBranch}
SCM-Revision=${commitHash}
SCM-Build-Time=${buildTimestamp}
GroupId=${project.groupId}
ArtifactId=${project.artifactId}
extensionVersion=${project.version}
extensionModifiedTime=${buildDate}
extensionBuildTime=${buildDate}
